### ISSUE TITLE
keypair issue

### ISSUE THREAD

**Issue by redragonx** [TheFixers/node-honeypot-client#1]
{"_id":{"$oid":"56e61ec584f4237ff17a9563"},"Client":{"IP":"127.0.0.1","Data":{"Username":"htyrrytrrre","Passwords":"yuytgfhtyry","Data":"uty6thuyyyyyyyyt || htg || exit || quit || fdssdsfs","Time":"20:15:06.837799"},"Port":"23","Socket":"47446"}}

theres commands from the data subarray

**Comment by joshcalafell** [comment]
I'll work on it. The json responses should be uniform though.

**Comment by joshcalafell** [comment]
Like, for example, I would make Data.Data an array of items, and also anything else that has multiple entries.

**Comment by joshcalafell** [comment]
"Data": { "Data": ["abc", "123", "xyz"] }

**Comment by joshcalafell** [comment]
Fixed
