### ISSUE TITLE
Implement Pagination

### ISSUE THREAD

**Issue by joshcalafell** [TheFixers/node-honeypot-client#25]

**Comment by redragonx** [comment]
I'll see if I can help here.

**Comment by joshcalafell** [comment]
On 2016-04-05 20:43, Stephen Chavez wrote:

> I'll see if I can help here.
> 
> ## 
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub [1]
> 
>   *
> 
> ## Links:
> 
> [1]
> https://github.com/TheFixers/node-honeypot-client/issues/25#issuecomment-205979201

No worries man, I'm about done with it, I don't want merge issues tbh... 
I got it... Plus, it needs to comply with flux... Thanks though
